# Generated by Django 4.1.7 on 2023-03-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_link_position',
            field=models.BooleanField(default=True),
        ),
    ]
