# Generated by Django 4.1.7 on 2023-03-31 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
        ('login', '0004_user_social_link_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theme.theme'),
        ),
    ]
