# Generated by Django 4.1.7 on 2023-03-28 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(max_length=50)),
                ('gmail', models.EmailField(max_length=50)),
                ('telegram', models.URLField(max_length=150)),
                ('tiktok', models.URLField(max_length=150)),
                ('spotify', models.URLField(max_length=150)),
                ('facebook', models.URLField(max_length=150)),
                ('linkdin', models.URLField(max_length=150)),
                ('pinterest', models.URLField(max_length=150)),
                ('youtube', models.URLField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
