# Generated by Django 4.1.7 on 2023-03-31 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socials', '0002_socialicons_usersocials_delete_socialicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocials',
            name='position',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='usersocials',
            unique_together={('user', 'social_icon')},
        ),
    ]
