# Generated by Django 4.1.7 on 2023-04-07 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socials', '0005_alter_usersocials_social_icon_alter_usersocials_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersocials',
            name='social_icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icon', to='socials.socialicons'),
        ),
        migrations.AlterField(
            model_name='usersocials',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to=settings.AUTH_USER_MODEL),
        ),
    ]
