# Generated by Django 4.1.7 on 2023-03-31 09:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0002_alter_userlink_links'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlink',
            unique_together={('user', 'link_key')},
        ),
    ]
