# Generated by Django 4.1.7 on 2023-03-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_userlink_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlink',
            name='position',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userlink',
            name='thumbnail_url',
            field=models.URLField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='userlink',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
