# Generated by Django 4.1.7 on 2023-04-03 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_alter_userlink_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlink',
            name='link_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_name', to='links.link'),
        ),
    ]
